<a href="https://colab.research.google.com/github/amarsinghen/Learning_Equality_Curriculum_Recommendations/blob/main/Learning_Equality_Curriculum_Recommendations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!lscpu

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           79
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
Stepping:                        0
CPU MHz:                         2200.156
BogoMIPS:                        4400.31
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        256 KiB
L3 cache:                        55 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and use
                                 rcopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PB
                                 RSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtr
                                 r pge mca cmov pat pse36 clflush mmx fxsr sse s
                                 se2 ss ht syscall nx pdpe1gb rdtscp lm constant
                                 _tsc rep_good nopl xtopology nonstop_tsc cpuid
                                 tsc_known_freq pni pclmulqdq ssse3 fma cx16 pci
                                 d sse4_1 sse4_2 x2apic movbe popcnt aes xsave a
                                 vx f16c rdrand hypervisor lahf_lm abm 3dnowpref
                                 etch invpcid_single ssbd ibrs ibpb stibp fsgsba
                                 se tsc_adjust bmi1 hle avx2 smep bmi2 erms invp
                                 cid rtm rdseed adx smap xsaveopt arat md_clear
                                 arch_capabilities

In [2]:
!pip install -q kaggle

In [3]:
# The Kaggle API client expects this file to be in ~/.kaggle,
# so move it there.
!mkdir -p ~/.kaggle
!cp '/content/drive/My Drive/kaggle.json' ~/.kaggle/
# This permissions change avoids a warning on Kaggle tool startup.
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
# Downloading the data from kaggle for first time, and 
# then saving to google drive for future uses. It is faster this way
!kaggle competitions download -c learning-equality-curriculum-recommendations

Downloading learning-equality-curriculum-recommendations.zip to /content
 97% 247M/254M [00:02<00:00, 137MB/s]
100% 254M/254M [00:02<00:00, 131MB/s]

In [5]:
import zipfile
import pandas as pd

In [6]:
local_zip = ['learning-equality-curriculum-recommendations.zip']
for i in range(len(local_zip)):
    zip_ref = zipfile.ZipFile(local_zip[i], 'r')
    zip_ref.extractall('/tmp')
    zip_ref.close()

In [7]:
content_df = pd.read_csv('/tmp/content.csv')

In [8]:
print(f"content_df shape: {content_df.shape}")
print(f"content_df columns : {content_df.columns}")
content_df.head(20)

content_df shape: (154047, 8)
content_df columns : Index(['id', 'title', 'description', 'kind', 'text', 'language',
       'copyright_holder', 'license'],
      dtype='object')

,id,title,description,kind,text,language,copyright_holder,license
0,c_00002381196d,"Sumar números de varios dígitos: 48,029+233,930","Suma 48,029+233,930 mediante el algoritmo está...",video,NaN,es,NaN,NaN
1,c_000087304a9e,Trovare i fattori di un numero,Sal trova i fattori di 120.\n\n,video,NaN,it,NaN,NaN
2,c_0000ad142ddb,Sumar curvas de demanda,Cómo añadir curvas de demanda\n\n,video,NaN,es,NaN,NaN
3,c_0000c03adc8d,Nado de aproximação,Neste vídeo você vai aprender o nado de aproxi...,document,\nNado de aproximação\nSaber nadar nas ondas ...,pt,Sikana Education,CC BY-NC-ND
4,c_00016694ea2a,geometry-m3-topic-a-overview.pdf,geometry-m3-topic-a-overview.pdf,document,Estándares Comunes del Estado de Nueva York\n\...,es,Engage NY,CC BY-NC-SA
5,c_00019840d110,5.12E: Regulation of the Calvin Cycle,NaN,html5,LEARNING OBJECTIVES\n\nOutline the three major...,en,CSU and Merlot,CC BY-NC-SA
6,c_0001ec56e20f,Reflexionemos sobre lo que vemos y escuchamos,NaN,document,Lección\n\n7\n\nReflexionemos sobre lo que\nve...,es,Publicado por el Lic. Edelberto Andino(edelber...,CC BY-NC-SA
7,c_00025aaa1533,अंग्रेजी ओके प्लीज 1.2,source_url=http://www.prathamopenschool.org/Co...,video,NaN,mr,NaN,NaN
8,c_00027d03ca7d,4.E: Genomes and Chromosomes (Exercises),NaN,html5,4.3\n\n(BPA) Answer the following questions wi...,en,CSU and Merlot,CC BY-NC-SA
9,c_000314eb850f,La banca 12: los bonos del tesoro (deuda pública),Introducción a la deuda y los fondos públicos....,video,NaN,es,NaN,NaN
10,c_000425df0161,9.3: Van Der Waals Forces between Atoms,NaN,html5,Introduction\n\nThe perfect gas equation of st...,en,CSU and Merlot,CC BY-NC-SA
11,c_00046806ad8a,Compare multi-digit numbers,Use your place value skills to practice compar...,exercise,NaN,en,NaN,NaN
12,c_0005765779c8,Ендомембранна система,"Преглед на мембранните структури, които образу...",video,В това видео ще разгледаме ендомембранната сис...,bg,Khan Academy,CC BY-NC-SA
13,c_000644057f59,સમક્ષિતિજ પ્રક્ષિપ્ત માટે શુદ્ધ ગતિવિજ્ઞાનના સ...,જયારે સદિશના સમક્ષિતિજ અને શિરોલંબ ઘટક આપેલા હ...,exercise,NaN,gu,NaN,NaN
14,c_00068709797c,Kuhesabu vizio mraba kutafuta kanuni ya eneo,Sal anatumia kizio mraba kuona kwa nini kuzidi...,video,"Nina mistatili mitatu hapa, na pia nina vipimo...",sw,Khan Academy,CC BY-NC-SA
15,c_0006da6ff852,आधे और चौथाई,Practice dividing shapes into 2 or 4 equal sec...,exercise,NaN,hi,NaN,NaN
16,c_0006ec4d828a,बहुपदों को जोड़ना,NaN,exercise,NaN,hi,NaN,NaN
17,c_0006f51dc8e7,Lección 13,Objetivo: multiplicar factores numéricos mixto...,document,Lesson 13 5\n\nNYS COMMON CORE MATHEMATICS CUR...,es,Engage NY,CC BY-NC-SA
18,c_000751f58836,Tangents of circles problem (example 2),Sal finds a missing angle using the property t...,video,Angle A is a circumscribed angle on circle O. ...,en,Khan Academy,CC BY-NC-SA
19,c_0007d37600f3,Momento dipolar,Prevendo o momento de dipolo baseado na geomet...,video,NaN,pt,NaN,NaN

In [9]:
topics_df = pd.read_csv('/tmp/topics.csv')

In [10]:
print(f"topics_df shape : {topics_df.shape}")
print(f"topics_df columns : {topics_df.columns}")
topics_df.head(20)

topics_df shape : (76972, 9)
topics_df columns : Index(['id', 'title', 'description', 'channel', 'category', 'level',
       'language', 'parent', 'has_content'],
      dtype='object')

,id,title,description,channel,category,level,language,parent,has_content
0,t_00004da3a1b2,Откриването на резисторите,"Изследване на материали, които предизвикват на...",000cf7,source,4,bg,t_16e29365b50d,True
1,t_000095e03056,Unit 3.3 Enlargements and Similarities,NaN,b3f329,aligned,2,en,t_aa32fb6252dc,False
2,t_00068291e9a4,Entradas e saídas de uma função,Entenda um pouco mais sobre funções.,8e286a,source,4,pt,t_d14b6c2a2b70,True
3,t_00069b63a70a,Transcripts,NaN,6e3ba4,source,3,en,t_4054df11a74e,True
4,t_0006d41a73a8,Графики на експоненциални функции (Алгебра 2 н...,Научи повече за графиките на сложните показате...,000cf7,source,4,bg,t_e2452e21d252,True
5,t_0008768bdee6,100 સુધીનો સરવાળો,37 અને 49 જેવી બે-અંકની સંખ્યાઓ ઉમેરતા શીખો.,5223e0,supplemental,4,gu,t_0da7a331d666,True
6,t_0008a1bd84ba,12. 20: Bird Reproduction,NaN,ebc86c,supplemental,5,en,t_c44ac9711007,True
7,t_000c0c854f0b,Nepal,NaN,f2e966,source,1,en,t_f9c4ef0d6290,False
8,t_000d1fb3f2f5,2.1.2 - Logarithms,NaN,e77b55,aligned,5,en,t_b897d168db90,True
9,t_000feba42136,As vacinas,NaN,8e286a,source,4,pt,t_dfc8ec591573,True
10,t_00102869fbcb,Triangles and polygons,Learning outcomes: students must be able to so...,a91e32,aligned,3,en,t_039cecc12bb8,True
11,t_0010852b7049,Divisão com vários algarismos,You know your multiplication tables and are ge...,8e286a,source,4,pt,t_33355476f050,True
12,t_001139e52dbe,Addition and Subtraction to 20,NaN,fef095,source,5,en,t_f078c5cdba92,False
13,t_0012a45fa09c,Quiz: materials and techniques,NaN,2ee29d,aligned,4,en,t_6957d4a9f469,True
14,t_001394e54503,သူငယ်တန်း,သူငယ်တန်းသင်္ချာ - ရေတွက်ခြင်း၊ အခြေခံဖြည့်စွက...,bff3ab,source,2,my,t_45fd32806f7d,False
15,t_001477394250,Part II - Computational Thinking - Advanced,NaN,c6dab5,source,2,en,t_9a2cd1d5f242,False
16,t_0014be0167f3,折旧和摊销,你如何解释“用完”的东西或应随着时间摊销的成本。本教程将为你提供答案。折旧和摊销听起来很“高...,f83dcf,source,4,zh,t_05757e2f8841,True
17,t_0014d6945f7e,يحدّد بعض قواعد الاشتقاق: يجد مشتقة اقتران باس...,5acb7211ecf6d9049f561089,9fd860,source,3,ar,t_48e4fb5d42e1,True
18,t_001558da4876,గాలి మరియు నీరు,source_id=LES1116,217993,source,5,te,t_78ba1e431c39,True
19,t_0015856edda8,Javascript,NaN,fc9105,supplemental,5,es,t_121a47996712,False

In [11]:
correlations_df = pd.read_csv('/tmp/correlations.csv')

In [12]:
print(f"correlations_df shape : {correlations_df.shape}")
print(f"correlations_df columns : {correlations_df.columns}")
correlations_df.head(20)

correlations_df shape : (61517, 2)
correlations_df columns : Index(['topic_id', 'content_ids'], dtype='object')

          topic_id                                        content_ids
0   t_00004da3a1b2  c_1108dd0c7a5d c_376c5a8eb028 c_5bc0e1e2cba0 c...
1   t_00068291e9a4  c_639ea2ef9c95 c_89ce9367be10 c_ac1672cdcd2c c...
2   t_00069b63a70a                                     c_11a1dc0bfb99
3   t_0006d41a73a8  c_0c6473c3480d c_1c57a1316568 c_5e375cf14c47 c...
4   t_0008768bdee6       c_34e1424229b4 c_7d1a964d66d5 c_aab93ee667f4
5   t_0008a1bd84ba                      c_7ff92a954a3d c_8790b074383e
6   t_000d1fb3f2f5  c_07f1d0eec4b2 c_15a6fb858696 c_175e9db3fc44 c...
7   t_000feba42136                      c_2bbc650030f4 c_304ee4f59410
8   t_00102869fbcb  c_005e793bd0c5 c_066737fa5146 c_08b2070f92e0 c...
9   t_0010852b7049  c_0baf72ed7e1e c_5eca28e2cdb4 c_6a5472fb1483 c...
10  t_0012a45fa09c                                     c_dde078b8ea7a
11  t_0014be0167f3  c_2ae5bd6b746a c_370dec1b1ed5 c_5183486b4c6d c...
12  t_0014d6945f7e                      c_e1f4e63aa1c3 c_e50e1505b72c
13  t_001558da4876  c_108194db1545 c_363301ab3248 c_37e49b7105bc c...
14  t_0016d30772f3  c_061d9f90bb06 c_242ddc729eec c_61b851222e17 c...
15  t_0016fa92caf4                                     c_e1d73acfff8e
16  t_001a1575f24a                                     c_433f60c8c551
17  t_001bc7125ae7  c_057d90d1045b c_0a578d1828d0 c_0f6a7aa3e787 c...
18  t_001bcbb22694                                     c_1d9dfc709413
19  t_001bd01717d7  c_16f1cff519b3 c_289a31069ea7 c_6f0a3cf19895 c...

In [13]:
sample_submission_df = pd.read_csv('/tmp/sample_submission.csv')

In [14]:
print(f"sample_submission_df shape : {sample_submission_df.shape}")
print(f"sample_submission_df columns : {sample_submission_df.columns}")
sample_submission_df.head(20)

sample_submission_df shape : (5, 2)
sample_submission_df columns : Index(['topic_id', 'content_ids'], dtype='object')

         topic_id                                        content_ids
0  t_00004da3a1b2  c_1108dd0c7a5d c_376c5a8eb028 c_5bc0e1e2cba0 c...
1  t_00068291e9a4  c_639ea2ef9c95 c_89ce9367be10 c_ac1672cdcd2c c...
2  t_00069b63a70a                                     c_11a1dc0bfb99
3  t_0006d41a73a8  c_0c6473c3480d c_1c57a1316568 c_5e375cf14c47 c...
4  t_4054df11a74e                      c_3695c5dc1df6 c_f2d184a98231

In [15]:
example_data_point = correlations_df.loc[correlations_df['topic_id'].values=='t_00102869fbcb', 'content_ids'].values[0].split(" ")
print(example_data_point)
type(example_data_point)

['c_005e793bd0c5', 'c_066737fa5146', 'c_08b2070f92e0', 'c_0a0f0cfcd01a', 'c_0e3353b058f0', 'c_0eda77684335', 'c_0f16d374f415', 'c_10ca1869c758', 'c_10dbed87d839', 'c_11181d0b95aa', 'c_115c5b863574', 'c_1cd9f807f8e5', 'c_1f20565b1381', 'c_222e318d6d8a', 'c_29633da013a9', 'c_2cd238e941f1', 'c_30b3480d92f8', 'c_34bc70d326d5', 'c_3a12b23519f3', 'c_3a19935d0e70', 'c_3bc84cfa9818', 'c_3cf6ef1121e4', 'c_470dab588a4d', 'c_48562a9fd7a5', 'c_4a017a7b88b1', 'c_5471bafde27d', 'c_5838ba054863', 'c_5a3a979a3cd9', 'c_5bac5e027198', 'c_5f25b381c46a', 'c_5f4b5200a725', 'c_6062d2e46506', 'c_60ec15e6b535', 'c_65e1a1125573', 'c_683bd6b717fa', 'c_6a1b4e7d6de9', 'c_6a8228c8357e', 'c_6aef7c2f724c', 'c_6b9542168065', 'c_6f356bf86b85', 'c_6fee5dd33c0d', 'c_7265b169bc76', 'c_738debbd624a', 'c_7971ba5f03c4', 'c_7d1a59c7044d', 'c_7e2f3739ad0a', 'c_821fc6753fa7', 'c_8e29ba77df5b', 'c_8ee98ffbb4ec', 'c_91d5815c5c05', 'c_9520d0abdfe4', 'c_964f18665f78', 'c_97f7c60035ea', 'c_a0133f95e907', 'c_a5545a2ff5ca', 'c_a99a9622f854', 'c_b44c206ad756', 'c_b578b555904e', 'c_b6819b9c64df', 'c_b92a55cf1879', 'c_bebd175342f5', 'c_bef2c010d6f9', 'c_bef55777e57b', 'c_c69fc19ab8f2', 'c_cef9b08c48c4', 'c_d2cf189bb4ac', 'c_d32102fb335f', 'c_d4f5b6340aa5', 'c_d5606463f08a', 'c_d937c1b35bc7', 'c_dcf907ded334', 'c_def28d2e5eb0', 'c_df2bcd9b6fcc', 'c_e0b33b9e6118', 'c_e4262edc8daf', 'c_e7daeadb242c', 'c_e91ac93a2ea4', 'c_ebde478f5297', 'c_ecbdf2bb815b', 'c_ee6367296721', 'c_f16047c6f924', 'c_f32779fd55bb', 'c_f42f83d45a20', 'c_f567bb93578f', 'c_f56f6d8aef05', 'c_f9091a48e912', 'c_fbd300d2cc72']

list

In [16]:
topics_df.loc[topics_df['id']=='t_00102869fbcb']

,id,title,description,channel,category,level,language,parent,has_content
10,t_00102869fbcb,Triangles and polygons,Learning outcomes: students must be able to so...,a91e32,aligned,3,en,t_039cecc12bb8,True

In [17]:
topics_df.loc[topics_df['id']=='t_039cecc12bb8']

,id,title,description,channel,category,level,language,parent,has_content
1076,t_039cecc12bb8,"Space, shape and measurement",Learning outcomes: students must be able to so...,a91e32,aligned,2,en,t_5a5b745edd47,False

In [18]:
topics_df.loc[topics_df['id']=='t_5a5b745edd47']

,id,title,description,channel,category,level,language,parent,has_content
26966,t_5a5b745edd47,Form 1,This includes all the material relevant to the...,a91e32,aligned,1,en,t_bff0c73af728,False

In [19]:
topics_df.loc[topics_df['id']=='t_bff0c73af728']

,id,title,description,channel,category,level,language,parent,has_content
57457,t_bff0c73af728,Malawi Mathematics Syllabus,NaN,a91e32,aligned,0,en,NaN,True

In [20]:
content_df.loc[content_df['id'].isin(example_data_point)]

,id,title,description,kind,text,language,copyright_holder,license
214,c_005e793bd0c5,Regular and Irregular Polygons,NaN,html5,NaN,en,NaN,NaN
3801,c_066737fa5146,Classifying triangles based on its angles,A triangle is a closed figure consisting of th...,document,Classifying triangles based on its angles\nAlb...,en,MOE Malawi COVID19 Support Group,CC BY-SA
5134,c_08b2070f92e0,Classifying triangles,"Learn to categorize triangles as scalene, isos...",video,What I want to do in this video is talk about ...,en,Khan Academy,CC BY-NC-SA
5954,c_0a0f0cfcd01a,Using properties of quadrilaterals to solve pr...,A quadrilateral is a geometric figure with fou...,document,Using properties of quadrilaterals to solve\np...,en,MOE Malawi COVID19 Support Group,CC BY-SA
8506,c_0e3353b058f0,Polygon types,"concave vs convex, regular vs irregular polygons",exercise,NaN,en,NaN,NaN
...,...,...,...,...,...,...,...,...
147038,c_f42f83d45a20,Constructing Regular Polygons,"In this lesson, you are going to learn how to ...",document,"Constructing Regular Polygons\nMary Chagwa, Bl...",en,MOE Malawi COVID19 Support Group,CC BY-SA
147743,c_f567bb93578f,Parallelogram Classification,NaN,html5,NaN,en,NaN,NaN
147763,c_f56f6d8aef05,Determining the Unknown Angle in a Triangle,NaN,video,NaN,en,NaN,NaN
149874,c_f9091a48e912,Deriving the Formula for Interior Angles of a ...,"In this lesson, you are going to derive a form...",document,Deriving the Formula for Interior Angles of a\...,en,MOE Malawi COVID19 Support Group,CC BY-SA
151521,c_fbd300d2cc72,Interior Angles in Convex Polygons Practice,NaN,exercise,NaN,en,NaN,NaN

In [21]:
content_df

,id,title,description,kind,text,language,copyright_holder,license
0,c_00002381196d,"Sumar números de varios dígitos: 48,029+233,930","Suma 48,029+233,930 mediante el algoritmo está...",video,NaN,es,NaN,NaN
1,c_000087304a9e,Trovare i fattori di un numero,Sal trova i fattori di 120.\n\n,video,NaN,it,NaN,NaN
2,c_0000ad142ddb,Sumar curvas de demanda,Cómo añadir curvas de demanda\n\n,video,NaN,es,NaN,NaN
3,c_0000c03adc8d,Nado de aproximação,Neste vídeo você vai aprender o nado de aproxi...,document,\nNado de aproximação\nSaber nadar nas ondas ...,pt,Sikana Education,CC BY-NC-ND
4,c_00016694ea2a,geometry-m3-topic-a-overview.pdf,geometry-m3-topic-a-overview.pdf,document,Estándares Comunes del Estado de Nueva York\n\...,es,Engage NY,CC BY-NC-SA
...,...,...,...,...,...,...,...,...
154042,c_fffcbdd4de8b,2. 12: Diffusion,NaN,html5,What will eventually happen to these dyes?\n\n...,en,CSU and Merlot,CC BY-NC-SA
154043,c_fffe15a2d069,Sommare facendo gruppi da 10,Sal somma 5+68 spezzando il 5 in un 2 e un 3.\n\n,video,NaN,it,NaN,NaN
154044,c_fffed7b0d13a,Introdução à subtração,Sal fala sobre o que significa subtrair. Os ex...,video,NaN,pt,NaN,NaN
154045,c_ffff04ba7ac7,SA of a Cone,NaN,video,NaN,en,NaN,NaN
154046,c_ffffe5254266,The Jats,NaN,video,NaN,en,NaN,NaN

In [25]:
correlations_df.loc[correlations_df['topic_id'].isin(['t_039cecc12bb8','t_5a5b745edd47','t_bff0c73af728'])]

             topic_id                    content_ids
45922  t_bff0c73af728  c_019fa746becd c_be8df72e3e03

In [27]:
print('c_019fa746becd ' in example_data_point)
print('c_be8df72e3e03 ' in example_data_point)

False
False

In [22]:
result = pd.merge(content_df, topics_df, how="left", on=["key1", "key2"])

KeyError: ignored